name: Build Image & Push To Aliyun ACR

on:
  push:
    branches: [ "master" ]
env:
  # ACR信息
  ACR_REGISTRY: crpi-vyt22uhlh2w61g5u.cn-shanghai.personal.cr.aliyuncs.com  
  ACR_NAMESPACE: nmgkds
  IMAGE_REPO: myrepo
  # GitOps仓库信息
  GITOPS_REPO: "your-org/gitops-ack-config"
  GITOPS_APP_PATH: "apps/demo-service" # RepoB内应用yaml目录

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set variables
      run: |
        echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "SHORT_SHA=${{ github.sha }}" | cut -c1-7 >> $GITHUB_ENV
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ env.BRANCH }}-${{ env.SHORT_SHA }}" >> $GITHUB_ENV
        echo "FULL_IMAGE=${{ env.ACR_REGISTRY }}/${{ env.ACR_NAMESPACE }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV


    # - name: Config Docker registry mirror
    #   run: |
    #       sudo tee /etc/docker/daemon.json <<-'EOF'
    #       {
    #         "registry-mirrors": [
    #           "https://mirror.baidubce.com"
    #         ]
    #       }
    #       EOF
    #       sudo systemctl daemon-reload
    #       sudo systemctl restart docker

    - name: Login to Aliyun ACR
      run: |
          docker login \
          --username=${{ secrets.ACR_USERNAME }} \
          crpi-vyt22uhlh2w61g5u.cn-shanghai.personal.cr.aliyuncs.com \
          --password=${{ secrets.ACR_PASSWORD }}

    - name: Generate image meta
      id: meta
      run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_FULL=${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/${{ secrets.ALI_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV
    
    - name: Build & Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.FULL_IMAGE }}

    
    # - name: Build & Push Docker Image
    #   uses: docker/build-push-action@v5
    #   with:
    #       context: .
    #       push: true
    #       # 如果你的Dockerfile不在根目录 ，添加 file: ./app/Dockerfile
    #       tags: |
    #         ${{ env.IMAGE_FULL }}
    #         ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/${{ secrets.ALI_REPOSITORY }}:latest
    #       # ACK集群一般amd64，若需要arm架构自行修改
    #       platforms: linux/amd64
    #       # cache-from: type=registry,reference=${{ env.IMAGE_FULL }}
    #       # cache-to: type=registry,reference=${{ env.IMAGE_FULL }},mode=max


    # 7. 打印最终镜像地址，方便复制到ACK deployment
    - name: Output final image address
      run: |
          echo "✅ 镜像构建推送完成"
          echo "镜像地址：${{ env.FULL_IMAGE }}"

      
