name: Build Image & Push To Aliyun ACR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Config Docker registry mirror
      run: |
          sudo tee /etc/docker/daemon.json <<-'EOF'
          {
            "registry-mirrors": [
              "https://mirror.baidubce.com"
            ]
          }
          EOF
          sudo systemctl daemon-reload
          sudo systemctl restart docker

    - name: Login to Aliyun ACR
      run: |
          docker login \
          --username=${{ secrets.ACR_USERNAME }} \
          crpi-vyt22uhlh2w61g5u.cn-shanghai.personal.cr.aliyuncs.com \
          --password=${{ secrets.ACR_PASSWORD }}

    - name: Generate image meta
      id: meta
      run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV
          echo "IMAGE_FULL=${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/${{ secrets.ALI_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_ENV

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          # 如果你的Dockerfile不在根目录，添加 file: ./app/Dockerfile
          tags: |
            ${{ env.IMAGE_FULL }}
            ${{ secrets.ALI_REGISTRY }}/${{ secrets.ALI_NAMESPACE }}/${{ secrets.ALI_REPOSITORY }}:latest
          # ACK集群一般amd64，若需要arm架构自行修改
          platforms: linux/amd64
          # cache-from: type=registry,reference=${{ env.IMAGE_FULL }}
          # cache-to: type=registry,reference=${{ env.IMAGE_FULL }},mode=max


    # 7. 打印最终镜像地址，方便复制到ACK deployment
    - name: Output final image address
      run: |
          echo "✅ 镜像构建推送完成"
          echo "镜像地址：${{ env.IMAGE_FULL }}"

      
